#pragma once

#include <Parsers/IAST_fwd.h>
#include <Parsers/Prometheus/PrometheusQueryResultType.h>
#include <Parsers/Prometheus/PrometheusQueryTree.h>
#include <Storages/ColumnsDescription.h>
#include <Storages/TimeSeries/PrometheusQueryToSQL/ConverterConfig.h>


namespace DB::PrometheusQueryToSQL
{
using ResultType = PrometheusQueryResultType;

/// Converts a prometheus query to SQL.
class Converter
{
public:
    Converter(PrometheusQueryTree promql_tree_, ConverterConfig config_);

    ResultType getResultType() const { return result_type; }

    /// Returns the names and types of columns returned by the SQL query generated by function getSQL().
    ColumnsDescription getResultColumns() const;

    /// Builds an AST to execute this prometheus query.
    ASTPtr getSQL() const;

private:
    PrometheusQueryTree promql_tree;
    ConverterConfig config;
    ResultType result_type;
};

}
