#pragma once

#include <Interpreters/Context_fwd.h>
#include <Parsers/ASTViewTargets.h>


namespace DB
{
class ASTCreateQuery;
class ColumnsDescription;
struct TimeSeriesSettings;

/// Normalizes a TimeSeries table definition.
/// Adds missing columns to the definition and reorders all the columns in the canonical way.
/// Also adds engines of inner tables to the definition if they aren't specified yet.
void normalizeTimeSeriesDefinition(ASTCreateQuery & create_query, const ContextPtr & context);

/// Extracts and normalizes TimeSeries settings from a `CREATE TABLE` query,
/// filling in defaults for any settings not explicitly specified.
/// Returns true if the settings were changed.
bool normalizeTimeSeriesSettings(TimeSeriesSettings & settings, const ASTCreateQuery & create_query, const ContextPtr & context);

/// Builds the canonical column list for a TimeSeries table from the given columns and settings.
/// Reorders and fills in missing columns; also applies the default expression from settings to the `id` column.
/// Returns true if the columns were changed.
bool normalizeTimeSeriesColumns(ColumnsDescription & columns, const TimeSeriesSettings & settings);

/// Returns the inner engine definition for a given target table kind (`samples`, `tags`, or `metrics`),
/// either copied from an `AS <other_table>` source or generated by default.
/// Returns `nullptr` if the target is an external table and not an inner one.
boost::intrusive_ptr<ASTStorage> getTimeSeriesInnerEngine(ViewTarget::Kind target_kind, const ASTCreateQuery & create_query, const TimeSeriesSettings & settings, const ContextPtr & context);

}
