#pragma once


namespace DB
{

/// Converts a parsed prometheus query to SQL.
class PrometheusQueryToSQLConverter
{
public:
    using EvaluationTimeType = DateTime64;
    using IntervalType = Decimal64;

    struct TimeSeriesTableInfo
    {
        StorageID storage_id;
        DataTypePtr timestamp_data_type;
        DataTypePtr value_data_type;
    };

    PrometheusQueryToSQLConverter(const PrometheusQueryTree & promql_,
                                  const EvaluationTimeType & evaluation_time_,
                                  const TimeSeriesTableInfo & time_series_table_info_,
                                  const IntervalType & lookback_delta_,
                                  const IntervalType & default_resolution_);

    /// Builds an AST to execute this prometheus query.
    ASTPtr getSQL() const;

    /// Returns columns returned by the SQL query generated by function toSQL().
    ColumnsWithTypesAndNames getResultColumns() const;

private:
    class ASTBuilder;
    PrometheusQueryTree promql;
    EvaluationTimeType evaluation_time;
    TimeSeriesTableInfo time_series_table_info;
    IntervalType lookback_delta;
    IntervalType default_resolution;
};

}
