#pragma once


namespace DB
{

struct TimeSeriesColumnNames
{
    /// The "samples" table contains time series:
    static constexpr const char * ID = "id";

    /// Since version 2 a row of the "samples" table contains the samples of one time series within one time bucket:
    /// the column "samples" contains the samples sorted by timestamp as an array of tuples (timestamp, value),
    /// the column "bucket" contains the start of the bucket, and the columns "min_time" and "max_time"
    /// (declared below) contain the time range of the samples in the row.
    static constexpr const char * Samples = "samples";
    static constexpr const char * Bucket = "bucket";

    /// These names are also used for the columns returned by the table function prometheusQuery().
    /// Tables of versions before 2 store one sample per row in the "samples" table in the columns "timestamp" and "value".
    static constexpr const char * Timestamp = "timestamp";
    static constexpr const char * Value = "value";

    /// The "tags" table contains identifiers for each combination of a metric name with corresponding tags (labels):

    /// The default expression specified for the "id" column contains an expression for calculating an identifier of a time series by a metric name and tags.
    //static constexpr const char * kID = "id";
    static constexpr const char * MetricName = "metric_name";

    /// Contains all tags, including the "__name__" tag with the name of a metric and the tags
    /// which also have corresponding columns specified in the "tags_to_columns" setting.
    /// (In tables created by older versions this column contains only tags without corresponding columns
    /// and without the metric name, so reading must be able to handle both cases.)
    static constexpr const char * Tags = "tags";

    /// Contains the time range of a time series (in the "tags" table) or of the samples in a row (in the "samples" table).
    static constexpr const char * MinTime = "min_time";
    static constexpr const char * MaxTime = "max_time";

    /// The "metrics" table contains general information (metadata) about metrics:
    static constexpr const char * MetricFamily = "metric_family";
    static constexpr const char * Type = "type";
    static constexpr const char * Unit = "unit";
    static constexpr const char * Help = "help";

    /// Columns returned by the table function prometheusQuery().
    /// The function can also output columns `tags`, `value`, and `timestamp`.
    static constexpr const char * TimeSeries = "time_series";

    /// Internal columns used by steps of prometheus query evaluation.
    /// The function prometheusQuery() doesn't output them.
    static constexpr const char * Group = "group";
    static constexpr const char * NewGroup = "new_group";
    static constexpr const char * OriginalGroup = "original_group";
    static constexpr const char * JoinGroup = "join_group";
    static constexpr const char * JoinPresence = "join_presence";
    static constexpr const char * Values = "values";
    static constexpr const char * SelectedGroups = "selected_groups";
    static constexpr const char * StepsMask = "steps_mask";

    /// Old names kept for compatibility:

    /// The old name of the "metric_family" column, still used in the "metrics" target table.
    static constexpr const char * MetricFamilyName = "metric_family_name";

    /// Tables of version 0 declare it as an ephemeral column and used to fill it with all tags except the "__name__" tag,
    /// so identifiers generated for the same time series can differ from those generated by older versions.
    /// Since version 2 an id generator must not reference it.
    static constexpr const char * AllTags = "all_tags";
};

}
